-- 1. LOCATION_MASTER
CREATE TABLE IF NOT EXISTS LOCATION_MASTER (
    ZipCode VARCHAR(10) PRIMARY KEY,
    City VARCHAR(50) NOT NULL
);

-- 2. WARD
CREATE TABLE IF NOT EXISTS WARD (
    Ward_ID INT PRIMARY KEY,
    Ward_Name VARCHAR(100) NOT NULL,
    Population INT
);

-- 3. CATEGORY
CREATE TABLE IF NOT EXISTS CATEGORY (
    Category_ID INT PRIMARY KEY,
    Cat_Name VARCHAR(100) NOT NULL,
    Priority VARCHAR(20) CHECK (Priority IN ('Low', 'Medium', 'High'))
);

-- 4. DEPARTMENT
CREATE TABLE IF NOT EXISTS DEPARTMENT (
    Dept_ID INT PRIMARY KEY,
    Dept_Name VARCHAR(100) NOT NULL,
    Head_Officer VARCHAR(100)
);

-- 5. DEPT_HELPLINES
CREATE TABLE IF NOT EXISTS DEPT_HELPLINES (
    Dept_ID INT,
    Helpline_No VARCHAR(15),
    PRIMARY KEY (Dept_ID, Helpline_No),
    FOREIGN KEY (Dept_ID) REFERENCES DEPARTMENT (Dept_ID) ON DELETE CASCADE
);

-- 6. CITIZEN
CREATE TABLE IF NOT EXISTS CITIZEN (
    Citizen_ID SERIAL PRIMARY KEY,    -- Changed from INT to SERIAL for auto-incrementing IDs
    Fname VARCHAR(50) NOT NULL,
    Lname VARCHAR(50),
    Street VARCHAR(100),
    ZipCode VARCHAR(10),
    Phone VARCHAR(15) UNIQUE NOT NULL,
    Email VARCHAR(100) UNIQUE,
    FOREIGN KEY (ZipCode) REFERENCES LOCATION_MASTER(ZipCode)
);

-- 7. OFFICIAL
CREATE TABLE IF NOT EXISTS OFFICIAL (
    Official_ID INT PRIMARY KEY,
    Name VARCHAR(100) NOT NULL,
    Designation VARCHAR(50),
    Date_Joined DATE,
    Dept_ID INT,
    FOREIGN KEY (Dept_ID) REFERENCES DEPARTMENT (Dept_ID)
);

-- 8. COMPLAINT
CREATE TABLE IF NOT EXISTS COMPLAINT (
    Complaint_ID SERIAL PRIMARY KEY,  -- Assuming auto-increment
    Description TEXT NOT NULL,
    Status VARCHAR(20) DEFAULT 'Lodged' CHECK (Status IN ('Lodged', 'Assigned', 'In-Progress', 'Resolved', 'Closed', 'Dismissed')),
    GPS_Location VARCHAR(100),
    Citizen_ID INT NOT NULL,
    Category_ID INT NOT NULL,
    Ward_ID INT NOT NULL,
    FOREIGN KEY (Citizen_ID) REFERENCES CITIZEN(Citizen_ID),
    FOREIGN KEY (Category_ID) REFERENCES CATEGORY(Category_ID),
    FOREIGN KEY (Ward_ID) REFERENCES WARD(Ward_ID)
);

-- 9. ASSIGNMENT
CREATE TABLE IF NOT EXISTS ASSIGNMENT (
    Assignment_ID SERIAL PRIMARY KEY,
    Start_Date DATE DEFAULT CURRENT_DATE,
    Target_Date DATE,
    Complaint_ID INT UNIQUE NOT NULL,
    Official_ID INT NOT NULL,
    FOREIGN KEY (Complaint_ID) REFERENCES COMPLAINT(Complaint_ID),
    FOREIGN KEY (Official_ID) REFERENCES OFFICIAL(Official_ID)
);

-- 10. FEEDBACK
CREATE TABLE IF NOT EXISTS FEEDBACK (
    Complaint_ID INT,
    Feedback_No INT,
    Rating INT CHECK (Rating BETWEEN 1 AND 5),
    Comments TEXT,
    PRIMARY KEY (Complaint_ID, Feedback_No),
    FOREIGN KEY (Complaint_ID) REFERENCES COMPLAINT(Complaint_ID) ON DELETE CASCADE
);

-- 11. OFFICIAL_WARD_COVERAGE
CREATE TABLE IF NOT EXISTS OFFICIAL_WARD_COVERAGE (
    Official_ID INT,
    Ward_ID INT,
    PRIMARY KEY (Official_ID, Ward_ID),
    FOREIGN KEY (Official_ID) REFERENCES OFFICIAL(Official_ID),
    FOREIGN KEY (Ward_ID) REFERENCES WARD(Ward_ID)
);

-- 12. COMPLAINT_LOG (Added for Progress Tracking)
CREATE TABLE IF NOT EXISTS COMPLAINT_LOG (
    Log_ID SERIAL PRIMARY KEY,
    Complaint_ID INT NOT NULL,
    Status VARCHAR(20) NOT NULL,
    Change_Timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (Complaint_ID) REFERENCES COMPLAINT(Complaint_ID) ON DELETE CASCADE
);
